stages:
  - compile
  - test
  - cs

packaging:
  stage: compile
  script:
    # check for BOM - not working
    - if grep -rn './' -e "\xEF\xBB\xBF"; then exit 1; fi
    - echo 'Packaging of 1 package script should be called here'
    - mkdir tmp
    - mkdir tmp/packages
    - sed -n 's:.*<file.*?>\(.*\)</file>.*:\1:p' pkg_testimonials.xml
    - pwd
    - ls -la
  artifacts:
    paths:
    - testimonials.zip

test:
  stage: test
  script:
    - echo 'Tests go here'

codestyle:
  stage: cs
  script:
    - echo 'Code style checks go here'