stages:
  - compile
  - test
  - cs

packaging:
  stage: compile
  script:
    - echo 'Packaging of 1 package script should be called here'
  artifacts:
    paths:
    - testimonials.zip

packaging-pro:
  stage: compile
  script:
    - echo 'Packaging of 1 package script should be called here'
  artifacts:
    paths:
    - testimonials_pro.zip

test:
  stage: test
  script:
    - echo 'Tests go here'

codestyle:
  stage: cs
  script:
    - echo 'Code style checks go here'