stages:
  - compile
  - test
  - cs

packaging:
  stage: compile
  script:
    # check for BOM - not working
    # - find ./ -type f  -exec echo {} \;
    - echo 'Packaging of 1 package script should be called here'
    - mkdir tmp
    - mkdir tmp/packages
    - sed -n 's:.*<id>\(.*\)</id>.*:\1:p' pkg_testimonials.xml -exec echo {} \;
    - pwd
    - ls -la
  artifacts:
    paths:
    - testimonials.zip

test:
  stage: test
  script:
    - echo 'Tests go here'

codestyle:
  stage: cs
  script:
    - echo 'Code style checks go here'