before_script:
  - apt-get update -qq && apt-get install -y -qq zip

stages:
  - compile
  - test
  - cs

packaging:
  stage: compile
  script:
    # check for BOM - not working
    - if grep -rn './' -e "\xEF\xBB\xBF"; then exit 1; fi
    - echo 'Packaging of 1 package script should be called here'
    - mkdir tmp
    - mkdir tmp/packages
    - mkdir built
    - grep -E -o '<file.*>(.*?)</file>' ./pkg_testimonials.xml |  sed -E 's/<file[^>]+>|.zip<\/file>//g' | while read in; do if [ "$in" != 'plg_installer_joomplaceupdater' ]; then cd ./"$in"; zip -r ./../tmp/packages/"$in".zip ./*; cd ./../; fi; done
    - cp ./pkg_testimonials.xml ./tmp/pkg_testimonials.xml
    - cd ./tmp/
#    - zip -r ./../pkg_testimonials.zip ./*
#    - cd ./built/
    - pwd
  artifacts:
    paths:
    - tmp/
    name: "pkg_testimonials_$CI_BUILD_NAME"

test:
  stage: test
  script:
    - echo 'Tests go here'

codestyle:
  stage: cs
  script:
    - echo 'Code style checks go here'