stages:
  - compile
  - test
  - cs

packaging:
  stage: compile
  script:
    # check for BOM
    - find ./ -type f -exec sed '1s/^\xEF\xBB\xBF//' -i {} \; -exec rm {}.bak --interactive=never 2>/dev/null
    - echo 'Packaging of 1 package script should be called here'
    - pwd
    - ls -la
  artifacts:
    paths:
    - testimonials.zip

test:
  stage: test
  script:
    - echo 'Tests go here'

codestyle:
  stage: cs
  script:
    - echo 'Code style checks go here'